const tenantId = "ce8314ef-6870-49e7-88d2-1435505f684a";
const clientId = "6ab486ec-1a40-4563-8e41-3ea6705d5692";
const redirectUri = "https://mgordillo73.github.io/hub7-documentos/";
const scopes = ["User.Read", "Files.Read.All", "Sites.Read.All"];

const msalApp = new msal.PublicClientApplication({auth:{clientId,authority:`https://login.microsoftonline.com/${tenantId}`,redirectUri},cache:{cacheLocation:"sessionStorage",storeAuthStateInCookie:false}});
const authButton=document.querySelector("#auth-button"),welcomeLogin=document.querySelector("#welcome-login"),userLabel=document.querySelector("#user-label"),queryInput=document.querySelector("#query"),searchButton=document.querySelector("#search-button"),form=document.querySelector("#search-form"),welcome=document.querySelector("#welcome"),results=document.querySelector("#results");

function activeAccount(){return msalApp.getActiveAccount()||msalApp.getAllAccounts()[0]||null}
function setSignedIn(account){msalApp.setActiveAccount(account);userLabel.textContent=account.username;authButton.textContent="Salir";queryInput.disabled=false;searchButton.disabled=false;welcomeLogin.textContent="Buscar en SharePoint"}
function setSignedOut(){userLabel.textContent="Sin iniciar sesión";authButton.textContent="Entrar con Microsoft";queryInput.disabled=true;searchButton.disabled=true;welcomeLogin.textContent="Entrar con Microsoft"}
async function login(){try{const response=await msalApp.loginPopup({scopes,prompt:"select_account"});setSignedIn(response.account);queryInput.focus()}catch(error){showError("No se pudo iniciar sesión. Comprueba que utilizas tu cuenta corporativa de HUB7S.",error)}}
async function logout(){const account=activeAccount();if(account)await msalApp.logoutPopup({account,postLogoutRedirectUri:redirectUri});setSignedOut();reset()}
async function token(){const account=activeAccount();if(!account)throw new Error("Debes iniciar sesión.");try{return(await msalApp.acquireTokenSilent({account,scopes})).accessToken}catch{return(await msalApp.acquireTokenPopup({account,scopes})).accessToken}}
function escapeHtml(value=""){return value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function reset(){results.classList.add("hidden");results.innerHTML="";welcome.classList.remove("hidden");queryInput.value=""}
function showError(message,error){console.error(error);welcome.classList.add("hidden");results.classList.remove("hidden");results.innerHTML=`<div class="error"><strong>No se ha podido completar la consulta.</strong><p>${escapeHtml(message)}</p></div>`}
async function searchDocuments(searchText){welcome.classList.add("hidden");results.classList.remove("hidden");results.innerHTML='<div class="loading">Buscando en SharePoint…</div>';try{const accessToken=await token();const response=await fetch("https://graph.microsoft.com/v1.0/search/query",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({requests:[{entityTypes:["driveItem"],query:{queryString:searchText},from:0,size:25,fields:["name","webUrl","lastModifiedDateTime","file","parentReference"]}]})});if(!response.ok){const detail=await response.text();throw new Error(`${response.status}: ${detail}`)}const data=await response.json();const hits=data.value?.[0]?.hitsContainers?.flatMap(container=>container.hits||[])||[];renderResults(searchText,hits)}catch(error){showError("Microsoft no ha devuelto resultados. Revisa la sesión o inténtalo de nuevo.",error)}}
function renderResults(searchText,hits){if(!hits.length){results.innerHTML=`<h1>Resultados para “${escapeHtml(searchText)}”</h1><div class="empty">No se han encontrado documentos. Prueba con menos palabras o con el nombre del cliente.</div>`;return}results.innerHTML=`<h1>${hits.length} resultado${hits.length===1?"":"s"} para “${escapeHtml(searchText)}”</h1>`+hits.map(hit=>{const item=hit.resource||{},summary=(hit.summary||"Documento localizado en SharePoint.").replace(/<[^>]*>/g,""),date=item.lastModifiedDateTime?new Date(item.lastModifiedDateTime).toLocaleDateString("es-ES"):"";return `<article class="result-card"><h2>${escapeHtml(item.name||"Documento sin nombre")}</h2><p>${escapeHtml(summary)}</p><div class="result-meta"><span>${escapeHtml(date)}</span><a href="${escapeHtml(item.webUrl||"#")}" target="_blank" rel="noopener noreferrer">Abrir en SharePoint ↗</a></div></article>`}).join("")}

authButton.addEventListener("click",()=>activeAccount()?logout():login());welcomeLogin.addEventListener("click",()=>activeAccount()?queryInput.focus():login());form.addEventListener("submit",event=>{event.preventDefault();const q=queryInput.value.trim();if(q)searchDocuments(q)});document.querySelector("#new-search").addEventListener("click",reset);document.querySelectorAll("[data-query]").forEach(button=>button.addEventListener("click",()=>{queryInput.value=button.dataset.query;if(activeAccount())searchDocuments(button.dataset.query);else login()}));
const existing=activeAccount();existing?setSignedIn(existing):setSignedOut();
