const tenantId = "ce8314ef-6870-49e7-88d2-1435505f684a";
const clientId = "6ab486ec-1a40-4563-8e41-3ea6705d5692";
const redirectUri = "https://mgordillo73.github.io/hub7-documentos/";
const scopes = ["User.Read", "Files.Read.All", "Sites.Read.All"];

const msalApp = new msal.PublicClientApplication({auth:{clientId,authority:`https://login.microsoftonline.com/${tenantId}`,redirectUri},cache:{cacheLocation:"sessionStorage",storeAuthStateInCookie:false}});
const authButton=document.querySelector("#auth-button"),welcomeLogin=document.querySelector("#welcome-login"),userLabel=document.querySelector("#user-label"),queryInput=document.querySelector("#query"),micButton=document.querySelector("#mic-button"),searchButton=document.querySelector("#search-button"),form=document.querySelector("#search-form"),welcome=document.querySelector("#welcome"),results=document.querySelector("#results");

function activeAccount(){return msalApp.getActiveAccount()||msalApp.getAllAccounts()[0]||null}
function setSignedIn(account){msalApp.setActiveAccount(account);userLabel.textContent=account.username;authButton.textContent="Salir";queryInput.disabled=false;micButton.disabled=false;searchButton.disabled=false;welcomeLogin.textContent="Buscar en SharePoint"}
function setSignedOut(){userLabel.textContent="Sin iniciar sesión";authButton.textContent="Entrar con Microsoft";queryInput.disabled=true;micButton.disabled=true;searchButton.disabled=true;welcomeLogin.textContent="Entrar con Microsoft"}
async function login(){try{await msalApp.loginRedirect({scopes,prompt:"select_account"})}catch(error){showError("No se pudo iniciar sesión. Comprueba que utilizas tu cuenta corporativa de HUB7S.",error)}}
async function logout(){const account=activeAccount();if(account)await msalApp.logoutPopup({account,postLogoutRedirectUri:redirectUri});setSignedOut();reset()}
async function token(){const account=activeAccount();if(!account)throw new Error("Debes iniciar sesión.");try{return(await msalApp.acquireTokenSilent({account,scopes})).accessToken}catch{return(await msalApp.acquireTokenPopup({account,scopes})).accessToken}}
function escapeHtml(value=""){return value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function documentUrl(webUrl,mode){if(!webUrl)return "#";try{const url=new URL(webUrl);url.searchParams.delete("web");url.searchParams.delete("download");url.searchParams.set(mode==="download"?"download":"web","1");return url.toString()}catch{return webUrl}}
function reset(){results.classList.add("hidden");results.innerHTML="";welcome.classList.remove("hidden");queryInput.value=""}
function showError(message,error){console.error(error);welcome.classList.add("hidden");results.classList.remove("hidden");results.innerHTML=`<div class="error"><strong>No se ha podido completar la consulta.</strong><p>${escapeHtml(message)}</p></div>`}
function understandRequest(text){let query=text.trim().replace(/^(por favor[,.]?\s*)?(dime|dame|muéstrame|muestrame|enséñame|enseñame|busca|encuentra|quiero ver|necesito ver)\s+/i,"").replace(/^(todos?|todas?)\s+/i,"").trim();return query||text.trim()}
async function searchDocuments(searchText){const graphQuery=understandRequest(searchText);welcome.classList.add("hidden");results.classList.remove("hidden");results.innerHTML=`<div class="loading"><strong>Entendido.</strong> Estoy buscando ${escapeHtml(graphQuery)} en SharePoint…</div>`;try{const accessToken=await token();const response=await fetch("https://graph.microsoft.com/v1.0/search/query",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({requests:[{entityTypes:["driveItem"],query:{queryString:graphQuery},from:0,size:100,fields:["name","webUrl","lastModifiedDateTime","file","parentReference"]}]})});if(!response.ok){const detail=await response.text();throw new Error(`${response.status}: ${detail}`)}const data=await response.json();const hits=data.value?.[0]?.hitsContainers?.flatMap(container=>container.hits||[])||[];renderResults(searchText,hits,graphQuery)}catch(error){showError("Microsoft no ha devuelto resultados. Revisa la sesión o inténtalo de nuevo.",error)}}
function renderResults(searchText,hits,graphQuery=searchText){if(!hits.length){results.innerHTML=`<div class="assistant-answer"><strong>No he encontrado documentos que coincidan.</strong><p>He buscado “${escapeHtml(graphQuery)}”. Prueba con el nombre del cliente o con menos palabras.</p></div>`;return}results.innerHTML=`<div class="assistant-answer"><strong>He encontrado ${hits.length} documento${hits.length===1?"":"s"}.</strong><p>Estos son los resultados para “${escapeHtml(searchText)}”:</p></div>`+hits.map(hit=>{const item=hit.resource||{},summary=(hit.summary||"Documento localizado en SharePoint.").replace(/<[^>]*>/g,""),date=item.lastModifiedDateTime?new Date(item.lastModifiedDateTime).toLocaleDateString("es-ES"):"";return `<article class="result-card"><h2>${escapeHtml(item.name||"Documento sin nombre")}</h2><p>${escapeHtml(summary)}</p><div class="result-meta"><span>${escapeHtml(date)}</span><div class="result-actions"><a href="${escapeHtml(documentUrl(item.webUrl,"web"))}" target="_blank" rel="noopener noreferrer">Ver en SharePoint ↗</a><a class="download-link" href="${escapeHtml(documentUrl(item.webUrl,"download"))}" target="_blank" rel="noopener noreferrer">Descargar ↓</a></div></div></article>`}).join("")}

const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
let recognition=null;
function startDictation(){if(!SpeechRecognition){showError("El dictado no está disponible en este navegador. Prueba con Chrome o Edge.",new Error("SpeechRecognition no compatible"));return}if(recognition){recognition.stop();return}recognition=new SpeechRecognition();recognition.lang="es-ES";recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>{micButton.classList.add("listening");micButton.textContent="■";micButton.title="Detener dictado"};recognition.onresult=event=>{const spoken=event.results[0][0].transcript.trim();queryInput.value=spoken;if(spoken)searchDocuments(spoken)};recognition.onerror=event=>{if(event.error!=="aborted")showError(event.error==="not-allowed"?"Debes permitir el acceso al micrófono para utilizar el dictado.":"No he podido reconocer la voz. Inténtalo de nuevo.",event)};recognition.onend=()=>{micButton.classList.remove("listening");micButton.textContent="🎙";micButton.title="Dictar consulta";recognition=null};recognition.start()}
micButton.addEventListener("click",startDictation);
authButton.addEventListener("click",()=>activeAccount()?logout():login());welcomeLogin.addEventListener("click",()=>activeAccount()?queryInput.focus():login());form.addEventListener("submit",event=>{event.preventDefault();const q=queryInput.value.trim();if(q)searchDocuments(q)});document.querySelector("#new-search").addEventListener("click",reset);document.querySelectorAll("[data-query]").forEach(button=>button.addEventListener("click",()=>{queryInput.value=button.dataset.query;if(activeAccount())searchDocuments(button.dataset.query);else login()}));
async function start(){try{const response=await msalApp.handleRedirectPromise();if(response?.account)msalApp.setActiveAccount(response.account);const existing=activeAccount();existing?setSignedIn(existing):setSignedOut()}catch(error){setSignedOut();showError("No se pudo completar el inicio de sesión con Microsoft.",error)}}
start();
