const tenantId = "ce8314ef-6870-49e7-88d2-1435505f684a";
const clientId = "6ab486ec-1a40-4563-8e41-3ea6705d5692";
const redirectUri = "https://mgordillo73.github.io/hub7-documentos/";
const scopes = ["User.Read", "Files.Read.All", "Sites.Read.All"];
const homeSiteId="hub7s.sharepoint.com,e6e492d1-8753-466a-8c70-a3a14cfe6335,6e2696ff-08f0-430f-906a-2cf6db678e3a";
const documentsDriveId="b!0ZLk5lOHakaMcKOhTP5jNf-WJm7wCA9DkGos9ttnjjosATF7gwSHQJzMGmzT-r8t";
let metadataColumnMap=null;
let lastRenderedHits=[];

const msalApp = new msal.PublicClientApplication({auth:{clientId,authority:`https://login.microsoftonline.com/${tenantId}`,redirectUri},cache:{cacheLocation:"sessionStorage",storeAuthStateInCookie:false}});
const authButton=document.querySelector("#auth-button"),welcomeLogin=document.querySelector("#welcome-login"),userLabel=document.querySelector("#user-label"),queryInput=document.querySelector("#query"),micButton=document.querySelector("#mic-button"),searchButton=document.querySelector("#search-button"),scopeSelect=document.querySelector("#scope-select"),form=document.querySelector("#search-form"),welcome=document.querySelector("#welcome"),results=document.querySelector("#results");

function activeAccount(){return msalApp.getActiveAccount()||msalApp.getAllAccounts()[0]||null}
function setSignedIn(account){msalApp.setActiveAccount(account);userLabel.textContent=account.username;authButton.textContent="Salir";queryInput.disabled=false;micButton.disabled=false;searchButton.disabled=false;welcomeLogin.textContent="Buscar en SharePoint"}
function setSignedOut(){userLabel.textContent="Sin iniciar sesión";authButton.textContent="Entrar con Microsoft";queryInput.disabled=true;micButton.disabled=true;searchButton.disabled=true;welcomeLogin.textContent="Entrar con Microsoft"}
async function login(){try{await msalApp.loginRedirect({scopes,prompt:"select_account"})}catch(error){showError("No se pudo iniciar sesión. Comprueba que utilizas tu cuenta corporativa de HUB7S.",error)}}
async function logout(){const account=activeAccount();if(account)await msalApp.logoutPopup({account,postLogoutRedirectUri:redirectUri});setSignedOut();reset()}
async function token(){const account=activeAccount();if(!account)throw new Error("Debes iniciar sesión.");try{return(await msalApp.acquireTokenSilent({account,scopes})).accessToken}catch{return(await msalApp.acquireTokenPopup({account,scopes})).accessToken}}
function escapeHtml(value=""){return value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function documentUrl(webUrl,mode){if(!webUrl)return "#";try{const url=new URL(webUrl);url.searchParams.delete("web");url.searchParams.delete("download");url.searchParams.set(mode==="download"?"download":"web","1");return url.toString()}catch{return webUrl}}
function reset(){results.classList.add("hidden");results.innerHTML="";welcome.classList.remove("hidden");queryInput.value=""}
function showError(message,error){console.error(error);welcome.classList.add("hidden");results.classList.remove("hidden");results.innerHTML=`<div class="error"><strong>No se ha podido completar la consulta.</strong><p>${escapeHtml(message)}</p></div>`}
function understandRequest(text){let query=text.trim().replace(/^(por favor[,.]?\s*)?(dime|dame|muéstrame|muestrame|enséñame|enseñame|busca|encuentra|quiero ver|necesito ver)\s+/i,"").replace(/^(todos?|todas?)\s+/i,"").trim();return query||text.trim()}
function normalizeText(value=""){return String(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function flexibleSearchQuery(text){const plain=text.normalize("NFD").replace(/[\u0300-\u036f]/g,"");if(plain.toLocaleLowerCase("es-ES")===text.toLocaleLowerCase("es-ES"))return text;return `(${text}) OR (${plain})`}
function searchCore(text){const stop=new Set(["busca","buscar","dame","muestra","muestrame","ensename","las","los","una","unas","unos","realizada","realizadas","realizado","realizados","propuesta","propuestas","oferta","ofertas","presupuesto","presupuestos","para","entre","desde","hasta","del","de","al","el","la","en","y","que","se","han","hecho","hechas"]);const words=normalizeText(text).split(/[^a-z0-9]+/).filter(word=>word&&(!stop.has(word))&&!/^20\d{2}$/.test(word));return words.join(" ")||text}
function flattenValue(value){if(value==null)return "";if(Array.isArray(value))return value.map(flattenValue).join(" | ");if(typeof value==="object")return Object.values(value).map(flattenValue).join(" | ");return String(value)}
async function graphJson(url,accessToken,options={}){const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json",...(options.headers||{})}});if(!response.ok)throw new Error(`${response.status}: ${await response.text()}`);return response.json()}
async function getMetadataColumnMap(accessToken){if(metadataColumnMap)return metadataColumnMap;const list=await graphJson(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(documentsDriveId)}/list`,accessToken);const columns=await graphJson(`https://graph.microsoft.com/v1.0/sites/${encodeURIComponent(homeSiteId)}/lists/${list.id}/columns?$select=name,displayName`,accessToken);const wanted={"tipo de documento":"type","cliente":"client","tematica":"theme","ano de creacion":"year"};metadataColumnMap={};for(const column of columns.value||[]){const key=wanted[normalizeText(column.displayName)];if(key)metadataColumnMap[key]=column.name}return metadataColumnMap}
async function attachMetadata(accessToken,hits){const eligible=hits.filter(hit=>{const item=hit.resource||{};return item.id&&item.parentReference?.driveId===documentsDriveId});if(!eligible.length)return;let map={};try{map=await getMetadataColumnMap(accessToken)}catch(error){console.warn("No se pudieron resolver las columnas",error)}for(let offset=0;offset<eligible.length;offset+=20){const group=eligible.slice(offset,offset+20);try{const batch=await graphJson("https://graph.microsoft.com/v1.0/$batch",accessToken,{method:"POST",body:JSON.stringify({requests:group.map((hit,index)=>({id:String(index+1),method:"GET",url:`/drives/${encodeURIComponent(documentsDriveId)}/items/${encodeURIComponent(hit.resource.id)}/listItem/fields`}))})});for(const response of batch.responses||[]){const hit=group[Number(response.id)-1];if(!hit||response.status>=400)continue;const fields=response.body||{};const decodedName=name=>normalizeText(name.replace(/_x([0-9a-fA-F]{4})_/g,(_,hex)=>String.fromCharCode(parseInt(hex,16))));const aliases={type:["tipo de documento","tipodocumento"],client:["cliente"],theme:["tematica","tema"],year:["ano de creacion","anocreacion"]};const read=key=>{if(map[key]&&fields[map[key]]!=null)return flattenValue(fields[map[key]]);const candidate=Object.keys(fields).find(name=>aliases[key].some(alias=>decodedName(name).replace(/[^a-z0-9]/g,"").includes(alias.replace(/[^a-z0-9]/g,""))));return candidate?flattenValue(fields[candidate]):""};hit._metadata={type:read("type"),client:read("client"),theme:read("theme"),year:read("year")};hit._metadata.text=[hit._metadata.type,hit._metadata.client,hit._metadata.theme,hit._metadata.year].join(" | ")}}catch(error){console.warn("No se pudieron cargar algunos metadatos",error)}}}
function expandDocumentTypeQuery(text){const normalized=normalizeText(text);if(!/\b(propuesta|propuestas|oferta|ofertas)\b/.test(normalized))return text;const rest=text.replace(/\b(propuesta|propuestas|oferta|ofertas)\b/gi," ").replace(/\s+/g," ").trim();const equivalents="(propuesta OR propuestas OR oferta OR ofertas)";return rest?`(${rest}) AND ${equivalents}`:equivalents}
function scopeQuery(query){return query}
function inSelectedScope(hit){const item=hit.resource||{},driveId=item.parentReference?.driveId;if(driveId&&driveId!==documentsDriveId)return false;if(scopeSelect.value!=="proposals")return true;let location=normalizeText(item.parentReference?.path||"");try{location+=" "+normalizeText(decodeURIComponent(item.webUrl||""))}catch{location+=" "+normalizeText(item.webUrl||"")}return !location.trim()||location.includes("/propuestas")}
async function pagedGraph(url,accessToken){const values=[];let next=url;while(next){const page=await graphJson(next,accessToken);values.push(...(page.value||[]));next=page["@odata.nextLink"]||null}return values}
async function browseMatchingClientFolder(accessToken,query){if(scopeSelect.value!=="proposals")return[];try{const rootUrl=`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(documentsDriveId)}/root:/PROPUESTAS:/children?$top=200`;const rootItems=await pagedGraph(rootUrl,accessToken);const normalizedQuery=normalizeText(query);const folders=rootItems.filter(item=>item.folder).filter(item=>{const name=normalizeText(item.name);return name.length>2&&normalizedQuery.includes(name)}).sort((a,b)=>b.name.length-a.name.length);if(!folders.length)return[];const queue=[folders[0]],files=[],seen=new Set();while(queue.length&&files.length<500){const folder=queue.shift();if(seen.has(folder.id))continue;seen.add(folder.id);const children=await pagedGraph(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(documentsDriveId)}/items/${encodeURIComponent(folder.id)}/children?$top=200`,accessToken);for(const item of children){if(item.folder)queue.push(item);else if(item.file)files.push(item)}}return files.map(item=>({resource:item,summary:"Documento localizado directamente en la carpeta del cliente."}))}catch(error){console.warn("No se pudo explorar la carpeta del cliente",error);return[]}}
function metadataMatchesRequestedFilters(hit,query){const q=normalizeText(query),metadata=hit._metadata||{},item=hit.resource||{},name=normalizeText(item.name||""),type=normalizeText(metadata.type||"");let years=(q.match(/\b20\d{2}\b/g)||[]).map(Number);if(/\bultimo ano\b|\bultimos 12 meses\b/.test(q))years=[new Date().getFullYear()-1,new Date().getFullYear()];if(/\beste ano\b|\bano actual\b/.test(q))years=[new Date().getFullYear()];if(years.length){const source=[metadata.year,name,item.createdDateTime].filter(Boolean).join(" "),tagged=(source.match(/20\d{2}/g)||[]).map(Number);if(tagged.length&&!tagged.some(year=>year>=Math.min(...years)&&year<=Math.max(...years)))return false}if(/\bpresupuesto|presupuestos\b/.test(q)){if(type)return type.includes("presupuesto");return name.includes("presupuesto")}if(/\bpropuesta|propuestas|oferta|ofertas\b/.test(q)){if(type)return /propuesta|oferta/.test(type);return !name.includes("presupuesto")}return true}
async function searchDocuments(searchText){const graphQuery=understandRequest(searchText),apiQuery=searchCore(graphQuery);welcome.classList.add("hidden");results.classList.remove("hidden");results.innerHTML=`<div class="loading"><strong>Entendido.</strong> Estoy buscando ${escapeHtml(graphQuery)} en SharePoint…</div>`;try{const accessToken=await token();const response=await fetch("https://graph.microsoft.com/v1.0/search/query",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({requests:[{entityTypes:["driveItem"],query:{queryString:apiQuery},from:0,size:100,fields:["id","name","webUrl","lastModifiedDateTime","file","folder","parentReference"]}]})});if(!response.ok){const detail=await response.text();throw new Error(`${response.status}: ${detail}`)}const data=await response.json();let hits=(data.value?.[0]?.hitsContainers?.flatMap(container=>container.hits||[])||[]).filter(hit=>hit.resource?.file&&inSelectedScope(hit));const folderHits=await browseMatchingClientFolder(accessToken,graphQuery);const byId=new Map();for(const hit of [...hits,...folderHits]){const key=hit.resource?.id||hit.resource?.webUrl;if(key&&!byId.has(key))byId.set(key,hit)}hits=[...byId.values()];await attachMetadata(accessToken,hits);hits=hits.filter(hit=>!String(hit.resource?.name||"").startsWith("~$")&&metadataMatchesRequestedFilters(hit,graphQuery));renderResults(searchText,hits,graphQuery)}catch(error){showError("Microsoft no ha devuelto resultados. Revisa la sesión o inténtalo de nuevo.",error)}}
function priorityTerms(query){const q=query.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const groups=[["propuesta","propuestas","oferta","ofertas"],["presupuesto","presupuestos"],["presentacion","presentaciones","ppt","powerpoint"],["informe","informes","reporte","reportes"],["contrato","contratos","acuerdo","acuerdos"],["factura","facturas"],["formacion","formaciones","curso","cursos","taller","talleres"]];return groups.find(group=>group.some(term=>q.includes(term)))||[]}
function rankResults(hits,query){const q=normalizeText(query),years=(q.match(/\b20\d{2}\b/g)||[]).map(Number),yearMin=years.length?Math.min(...years):null,yearMax=years.length?Math.max(...years):null,typeTerms=priorityTerms(query),stop=new Set(["busca","buscar","dame","muestra","muestrame","ensename","las","los","una","unas","unos","realizada","realizadas","realizado","realizados","para","entre","desde","hasta","del","de","al","el","la","en","y","que","se","han","hecho","hechas"]);const terms=q.split(/[^a-z0-9]+/).filter(term=>term.length>1&&!stop.has(term)&&!/^20\d{2}$/.test(term));return hits.map((hit,index)=>{const item=hit.resource||{},name=normalizeText(item.name),path=normalizeText(item.parentReference?.path||""),summary=normalizeText((hit.summary||"").replace(/<[^>]*>/g,"")),meta=normalizeText(hit._metadata?.text||"");let metadataScore=0,folderScore=0,contentScore=0;for(const term of terms){if(meta.includes(term))metadataScore+=140;if(path.includes(term))folderScore+=45;if(name.includes(term))contentScore+=25;if(summary.includes(term))contentScore+=8}if(typeTerms.length){if(typeTerms.some(term=>meta.includes(term)))metadataScore+=220;else if(hit._metadata?.type)metadataScore-=120}if(yearMin!=null&&hit._metadata?.year){const taggedYears=(String(hit._metadata.year).match(/20\d{2}/g)||[]).map(Number);if(taggedYears.length){if(taggedYears.some(year=>year>=yearMin&&year<=yearMax))metadataScore+=220;else metadataScore-=500}}hit._matchReason=metadataScore>0?"Etiquetas":folderScore>0?"Carpeta":"Título o contenido";return {hit,index,score:metadataScore*10000+folderScore*100+contentScore}}).sort((a,b)=>b.score-a.score||a.index-b.index).map(entry=>entry.hit)}
function renderResults(searchText,hits,graphQuery=searchText){hits=rankResults(hits,graphQuery);lastRenderedHits=hits;if(!hits.length){results.innerHTML=`<div class="assistant-answer"><strong>No he encontrado documentos que coincidan.</strong><p>He buscado “${escapeHtml(graphQuery)}”. Prueba con el nombre del cliente o con menos palabras.</p></div>`;return}results.innerHTML=`<div class="assistant-answer"><strong>He encontrado ${hits.length} documento${hits.length===1?"":"s"}.</strong><p>Estos son los resultados para “${escapeHtml(searchText)}” en ${scopeSelect.value==="proposals"?"PROPUESTAS":"HOME"}:</p></div>`+hits.map((hit,index)=>{const item=hit.resource||{},summary=(hit.summary||"Documento localizado en SharePoint.").replace(/<[^>]*>/g,""),date=item.lastModifiedDateTime?new Date(item.lastModifiedDateTime).toLocaleDateString("es-ES"):"";return `<article class="result-card"><div class="match-reason">${escapeHtml(hit._matchReason||"Contenido")}</div><h2>${escapeHtml(item.name||"Documento sin nombre")}</h2><p>${escapeHtml(summary)}</p><div class="result-meta"><span>${escapeHtml(date)}</span><div class="result-actions"><a href="${escapeHtml(documentUrl(item.webUrl,"web"))}" target="_blank" rel="noopener noreferrer">Ver en SharePoint ↗</a><a class="download-link" href="${escapeHtml(documentUrl(item.webUrl,"download"))}" target="_blank" rel="noopener noreferrer">Descargar ↓</a></div></div><div class="summary-row"><button class="summary-button" type="button" data-summary-index="${index}">📄 Ver resumen rápido</button></div><div class="quick-summary hidden" id="quick-summary-${index}"></div></article>`}).join("")}

function buildQuickSummary(hit){const item=hit.resource||{},metadata=hit._metadata||{},fragment=(hit.summary||"").replace(/<[^>]*>/g,"").trim(),path=item.parentReference?.path||"",folder=path.includes("/")?decodeURIComponent(path.split("/").pop()||""):"";const rows=[];if(metadata.type)rows.push(["Tipo",metadata.type]);if(metadata.client)rows.push(["Cliente",metadata.client]);if(metadata.theme)rows.push(["Temática",metadata.theme]);if(metadata.year)rows.push(["Año",metadata.year]);if(folder)rows.push(["Carpeta",folder]);const metaHtml=rows.length?`<dl>${rows.map(([label,value])=>`<div><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(String(value))}</dd></div>`).join("")}</dl>`:"";const usefulFragment=fragment&&!fragment.startsWith("Documento localizado")?fragment:"SharePoint no ha generado un fragmento de contenido para este archivo.";return `<strong>Resumen rápido</strong>${metaHtml}<p>${escapeHtml(usefulFragment)}</p><small>Basado en las etiquetas y el fragmento indexado por SharePoint.</small>`}
results.addEventListener("click",event=>{const button=event.target.closest(".summary-button");if(!button)return;const index=Number(button.dataset.summaryIndex),panel=document.querySelector(`#quick-summary-${index}`),hit=lastRenderedHits[index];if(!panel||!hit)return;if(!panel.innerHTML)panel.innerHTML=buildQuickSummary(hit);panel.classList.toggle("hidden");button.textContent=panel.classList.contains("hidden")?"📄 Ver resumen rápido":"Ocultar resumen"});

const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
let recognition=null;
function startDictation(){if(!SpeechRecognition){showError("El dictado no está disponible en este navegador. Prueba con Chrome o Edge.",new Error("SpeechRecognition no compatible"));return}if(recognition){recognition.stop();return}recognition=new SpeechRecognition();recognition.lang="es-ES";recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>{micButton.classList.add("listening");micButton.textContent="■";micButton.title="Detener dictado"};recognition.onresult=event=>{const spoken=event.results[0][0].transcript.trim();queryInput.value=spoken;if(spoken)searchDocuments(spoken)};recognition.onerror=event=>{if(event.error!=="aborted")showError(event.error==="not-allowed"?"Debes permitir el acceso al micrófono para utilizar el dictado.":"No he podido reconocer la voz. Inténtalo de nuevo.",event)};recognition.onend=()=>{micButton.classList.remove("listening");micButton.textContent="🎙";micButton.title="Dictar consulta";recognition=null};recognition.start()}
micButton.addEventListener("click",startDictation);
authButton.addEventListener("click",()=>activeAccount()?logout():login());welcomeLogin.addEventListener("click",()=>activeAccount()?queryInput.focus():login());form.addEventListener("submit",event=>{event.preventDefault();const q=queryInput.value.trim();if(q)searchDocuments(q)});document.querySelector("#new-search").addEventListener("click",reset);document.querySelectorAll("[data-query]").forEach(button=>button.addEventListener("click",()=>{queryInput.value=button.dataset.query;if(activeAccount())searchDocuments(button.dataset.query);else login()}));
async function start(){try{const response=await msalApp.handleRedirectPromise();if(response?.account)msalApp.setActiveAccount(response.account);const existing=activeAccount();existing?setSignedIn(existing):setSignedOut()}catch(error){setSignedOut();showError("No se pudo completar el inicio de sesión con Microsoft.",error)}}
start();
